version: "2.1"
services:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /usr/src:/config
      - /usr/src:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
